import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";

const cinaGeo = localfont({
  src: [
    {
      path: "../../public/fonts/CinaGEOTest-Light.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/CinaGEOTest-Regular.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/CinaGEOTest-Medium.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/CinaGEOTest-SemiBold.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/CinaGEOTest-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-cinaGeo",
});

export const metadata: Metadata = {
  title: "magelangKu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cinaGeo.variable}`}>
      <body className="flex flex-col items-center">{children}</body>
    </html>
  );
}
